"""create_cage_config_changes_log_table

Revision ID: e4da87a064dc
Revises: 4dac0ac3466c
Create Date: 2025-11-24 20:23:24.917223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4da87a064dc'
down_revision: Union[str, Sequence[str], None] = '4dac0ac3466c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cage_config_changes_log',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index(op.f('ix_cage_config_changes_log_cage_id'), 'cage_config_changes_log', ['cage_id'], unique=False)
    op.create_index(op.f('ix_cage_config_changes_log_created_at'), 'cage_config_changes_log', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cage_config_changes_log_created_at'), table_name='cage_config_changes_log')
    op.drop_index(op.f('ix_cage_config_changes_log_cage_id'), table_name='cage_config_changes_log')
    op.drop_table('cage_config_changes_log')
    # ### end Alembic commands ###
