"""initial schema

Revision ID: 43c3d5e43561
Revises: 
Create Date: 2025-11-13 21:25:07.267828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43c3d5e43561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feeding_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('silos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('capacity_mg', sa.Integer(), nullable=False),
    sa.Column('stock_level_mg', sa.Integer(), nullable=False),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blowers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('power_percentage', sa.Float(), nullable=False),
    sa.Column('blow_before_seconds', sa.Integer(), nullable=False),
    sa.Column('blow_after_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['feeding_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dosers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('silo_id', sa.Uuid(), nullable=True),
    sa.Column('doser_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dosing_rate_value', sa.Float(), nullable=False),
    sa.Column('dosing_rate_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_rate_value', sa.Float(), nullable=False),
    sa.Column('max_rate_value', sa.Float(), nullable=False),
    sa.Column('rate_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['feeding_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['silo_id'], ['silos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('fast_speed', sa.Float(), nullable=False),
    sa.Column('slow_speed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['feeding_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sensor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['feeding_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['feeding_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_assignments')
    op.drop_table('sensors')
    op.drop_table('selectors')
    op.drop_table('dosers')
    op.drop_table('blowers')
    op.drop_table('silos')
    op.drop_table('feeding_lines')
    op.drop_table('cages')
    # ### end Alembic commands ###
