"""add_feeding_operations_and_operation_events

Revision ID: e9caa22e0ade
Revises: fc42627a436f
Create Date: 2025-12-01 13:43:08.267007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e9caa22e0ade'
down_revision: Union[str, Sequence[str], None] = 'fc42627a436f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.Column('target_slot', sa.Integer(), nullable=False),
    sa.Column('target_amount_kg', sa.Float(), nullable=False),
    sa.Column('dispensed_kg', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('applied_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['feeding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeding_operations_cage_id'), 'feeding_operations', ['cage_id'], unique=False)
    op.create_index(op.f('ix_feeding_operations_session_id'), 'feeding_operations', ['session_id'], unique=False)
    op.create_index(op.f('ix_feeding_operations_started_at'), 'feeding_operations', ['started_at'], unique=False)
    op.create_index(op.f('ix_feeding_operations_status'), 'feeding_operations', ['status'], unique=False)
    op.create_table('operation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['feeding_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_events_operation_id'), 'operation_events', ['operation_id'], unique=False)
    op.create_index(op.f('ix_operation_events_timestamp'), 'operation_events', ['timestamp'], unique=False)
    op.drop_column('feeding_sessions', 'applied_strategy_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeding_sessions', sa.Column('applied_strategy_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_operation_events_timestamp'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_operation_id'), table_name='operation_events')
    op.drop_table('operation_events')
    op.drop_index(op.f('ix_feeding_operations_status'), table_name='feeding_operations')
    op.drop_index(op.f('ix_feeding_operations_started_at'), table_name='feeding_operations')
    op.drop_index(op.f('ix_feeding_operations_session_id'), table_name='feeding_operations')
    op.drop_index(op.f('ix_feeding_operations_cage_id'), table_name='feeding_operations')
    op.drop_table('feeding_operations')
    # ### end Alembic commands ###
