"""refactor_cage_line_direct_relationship

Revision ID: 69a72d3e5e93
Revises: a15c2ca60a44
Create Date: 2025-12-03 19:53:26.873196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a72d3e5e93'
down_revision: Union[str, Sequence[str], None] = 'a15c2ca60a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # PASO 1: Actualizar constraints de FKs en logs (CASCADE)
    op.drop_constraint(op.f('cage_biometry_log_cage_id_fkey'), 'cage_biometry_log', type_='foreignkey')
    op.create_foreign_key(None, 'cage_biometry_log', 'cages', ['cage_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cage_config_changes_log_cage_id_fkey'), 'cage_config_changes_log', type_='foreignkey')
    op.create_foreign_key(None, 'cage_config_changes_log', 'cages', ['cage_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cage_mortality_log_cage_id_fkey'), 'cage_mortality_log', type_='foreignkey')
    op.create_foreign_key(None, 'cage_mortality_log', 'cages', ['cage_id'], ['id'], ondelete='CASCADE')

    # PASO 2: Actualizar constraints de FKs en dosers y feeding_operations (SET NULL)
    op.drop_constraint(op.f('dosers_silo_id_fkey'), 'dosers', type_='foreignkey')
    op.create_foreign_key(None, 'dosers', 'silos', ['silo_id'], ['id'], ondelete='SET NULL')
    op.alter_column('feeding_operations', 'cage_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('feeding_operations_cage_id_fkey'), 'feeding_operations', type_='foreignkey')
    op.create_foreign_key(None, 'feeding_operations', 'cages', ['cage_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('feeding_sessions_line_id_fkey'), 'feeding_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'feeding_sessions', 'feeding_lines', ['line_id'], ['id'], ondelete='CASCADE')

    # PASO 3: Agregar columnas line_id y slot_number a cages (nullable)
    op.add_column('cages', sa.Column('line_id', sa.Uuid(), nullable=True))
    op.add_column('cages', sa.Column('slot_number', sa.Integer(), nullable=True))

    # PASO 4: Migrar datos de slot_assignments a cages
    op.execute("""
        UPDATE cages
        SET line_id = sa.line_id,
            slot_number = sa.slot_number
        FROM slot_assignments sa
        WHERE cages.id = sa.cage_id
    """)

    # PASO 5: Crear índice y FK constraint en cages.line_id
    op.create_index(op.f('ix_cages_line_id'), 'cages', ['line_id'], unique=False)
    op.create_foreign_key(None, 'cages', 'feeding_lines', ['line_id'], ['id'], ondelete='SET NULL')

    # PASO 6: Eliminar tabla slot_assignments
    op.drop_table('slot_assignments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ADVERTENCIA: Este downgrade NO migra datos de vuelta a slot_assignments
    # Los datos en cages.line_id y cages.slot_number se perderán

    # PASO 1: Recrear tabla slot_assignments (vacía)
    op.create_table('slot_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('line_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slot_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cage_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], name=op.f('slot_assignments_cage_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_id'], ['feeding_lines.id'], name=op.f('slot_assignments_line_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('slot_assignments_pkey'))
    )

    # PASO 2: Eliminar FK e índice de cages.line_id
    op.drop_constraint(None, 'cages', type_='foreignkey')
    op.drop_index(op.f('ix_cages_line_id'), table_name='cages')

    # PASO 3: Eliminar columnas de cages
    op.drop_column('cages', 'slot_number')
    op.drop_column('cages', 'line_id')

    # PASO 4: Revertir constraints de FKs
    op.drop_constraint(None, 'feeding_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('feeding_sessions_line_id_fkey'), 'feeding_sessions', 'feeding_lines', ['line_id'], ['id'])
    op.drop_constraint(None, 'feeding_operations', type_='foreignkey')
    op.create_foreign_key(op.f('feeding_operations_cage_id_fkey'), 'feeding_operations', 'cages', ['cage_id'], ['id'])
    op.alter_column('feeding_operations', 'cage_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'dosers', type_='foreignkey')
    op.create_foreign_key(op.f('dosers_silo_id_fkey'), 'dosers', 'silos', ['silo_id'], ['id'])
    op.drop_constraint(None, 'cage_mortality_log', type_='foreignkey')
    op.create_foreign_key(op.f('cage_mortality_log_cage_id_fkey'), 'cage_mortality_log', 'cages', ['cage_id'], ['id'])
    op.drop_constraint(None, 'cage_config_changes_log', type_='foreignkey')
    op.create_foreign_key(op.f('cage_config_changes_log_cage_id_fkey'), 'cage_config_changes_log', 'cages', ['cage_id'], ['id'])
    op.drop_constraint(None, 'cage_biometry_log', type_='foreignkey')
    op.create_foreign_key(op.f('cage_biometry_log_cage_id_fkey'), 'cage_biometry_log', 'cages', ['cage_id'], ['id'])
    # ### end Alembic commands ###
