"""create_cage_mortality_log_table

Revision ID: 4dac0ac3466c
Revises: 0a6c8b784c3d
Create Date: 2025-11-24 16:59:31.698780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dac0ac3466c'
down_revision: Union[str, Sequence[str], None] = '0a6c8b784c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cage_mortality_log',
    sa.Column('mortality_id', sa.Uuid(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.Column('dead_fish_count', sa.Integer(), nullable=False),
    sa.Column('mortality_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ),
    sa.PrimaryKeyConstraint('mortality_id')
    )
    op.create_index(op.f('ix_cage_mortality_log_cage_id'), 'cage_mortality_log', ['cage_id'], unique=False)
    op.create_index(op.f('ix_cage_mortality_log_mortality_date'), 'cage_mortality_log', ['mortality_date'], unique=False)
    op.drop_column('cage_biometry_log', 'sampled_fish_count')
    op.drop_column('cage_biometry_log', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cage_biometry_log', sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cage_biometry_log', sa.Column('sampled_fish_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cage_mortality_log_mortality_date'), table_name='cage_mortality_log')
    op.drop_index(op.f('ix_cage_mortality_log_cage_id'), table_name='cage_mortality_log')
    op.drop_table('cage_mortality_log')
    # ### end Alembic commands ###
