"""correcion cascade

Revision ID: a15c2ca60a44
Revises: e9caa22e0ade
Create Date: 2025-12-03 10:50:08.734918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15c2ca60a44'
down_revision: Union[str, Sequence[str], None] = 'e9caa22e0ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('slot_assignments_cage_id_fkey'), 'slot_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'slot_assignments', 'cages', ['cage_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slot_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('slot_assignments_cage_id_fkey'), 'slot_assignments', 'cages', ['cage_id'], ['id'])
    # ### end Alembic commands ###
