"""create_cage_biometry_log_table

Revision ID: 0a6c8b784c3d
Revises: ec0ecafb16cc
Create Date: 2025-11-21 16:04:16.008226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a6c8b784c3d'
down_revision: Union[str, Sequence[str], None] = 'ec0ecafb16cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cage_biometry_log',
    sa.Column('biometry_id', sa.Uuid(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.Column('old_fish_count', sa.Integer(), nullable=True),
    sa.Column('old_average_weight_g', sa.Float(), nullable=True),
    sa.Column('new_fish_count', sa.Integer(), nullable=True),
    sa.Column('new_average_weight_g', sa.Float(), nullable=True),
    sa.Column('sampled_fish_count', sa.Integer(), nullable=True),
    sa.Column('sampling_date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ),
    sa.PrimaryKeyConstraint('biometry_id')
    )
    op.create_index(op.f('ix_cage_biometry_log_cage_id'), 'cage_biometry_log', ['cage_id'], unique=False)
    op.drop_column('cages', 'initial_fish_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cages', sa.Column('initial_fish_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cage_biometry_log_cage_id'), table_name='cage_biometry_log')
    op.drop_table('cage_biometry_log')
    # ### end Alembic commands ###
