"""add_cage_population_and_config_fields

Revision ID: 483c40c16b03
Revises: 6ddfb40491ca
Create Date: 2025-11-20 15:24:03.145034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483c40c16b03'
down_revision: Union[str, Sequence[str], None] = '6ddfb40491ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cages', sa.Column('initial_fish_count', sa.Integer(), nullable=True))
    op.add_column('cages', sa.Column('current_fish_count', sa.Integer(), nullable=True))
    op.add_column('cages', sa.Column('avg_fish_weight_mg', sa.Integer(), nullable=True))
    op.add_column('cages', sa.Column('fcr', sa.Float(), nullable=True))
    op.add_column('cages', sa.Column('total_volume_m3', sa.Float(), nullable=True))
    op.add_column('cages', sa.Column('max_density_kg_m3', sa.Float(), nullable=True))
    op.add_column('cages', sa.Column('feeding_table_id', sa.String(length=50), nullable=True))
    op.add_column('cages', sa.Column('transport_time_sec', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cages', 'transport_time_sec')
    op.drop_column('cages', 'feeding_table_id')
    op.drop_column('cages', 'max_density_kg_m3')
    op.drop_column('cages', 'total_volume_m3')
    op.drop_column('cages', 'fcr')
    op.drop_column('cages', 'avg_fish_weight_mg')
    op.drop_column('cages', 'current_fish_count')
    op.drop_column('cages', 'initial_fish_count')
    # ### end Alembic commands ###
