"""create users table

Revision ID: 08b43ca26a82
Revises: b5b65f23cf32
Create Date: 2026-07-01 15:40:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08b43ca26a82"
down_revision: Union[str, Sequence[str], None] = "b5b65f23cf32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Si existe una tabla users previa con estructura antigua (por ejemplo,
    # de un intento anterior), la renombramos para preservar sus datos y
    # creamos la tabla acorde al modelo actual.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'users' AND table_schema = CURRENT_SCHEMA()
            ) AND EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'users'
                  AND table_schema = CURRENT_SCHEMA()
                  AND column_name = 'password_salt'
            ) THEN
                ALTER TABLE users RENAME TO users_legacy;
            END IF;
        END $$;
        """
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_superadmin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
