"""add doser_id and silo_id to cage_feedings

Revision ID: 2b2958c0b223
Revises: a1c83d7f0c16
Create Date: 2026-02-18 11:29:37.345531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2958c0b223'
down_revision: Union[str, Sequence[str], None] = 'a1c83d7f0c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cage_feedings', sa.Column('doser_id', sa.Uuid(), nullable=True))
    op.add_column('cage_feedings', sa.Column('silo_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_cage_feedings_doser_id'), 'cage_feedings', ['doser_id'], unique=False)
    op.create_index(op.f('ix_cage_feedings_silo_id'), 'cage_feedings', ['silo_id'], unique=False)
    op.create_foreign_key(None, 'cage_feedings', 'silos', ['silo_id'], ['id'])
    op.create_foreign_key(None, 'cage_feedings', 'dosers', ['doser_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cage_feedings', type_='foreignkey')
    op.drop_constraint(None, 'cage_feedings', type_='foreignkey')
    op.drop_index(op.f('ix_cage_feedings_silo_id'), table_name='cage_feedings')
    op.drop_index(op.f('ix_cage_feedings_doser_id'), table_name='cage_feedings')
    op.drop_column('cage_feedings', 'silo_id')
    op.drop_column('cage_feedings', 'doser_id')
    # ### end Alembic commands ###
