"""add current_power to blower

Revision ID: 897baf33d221
Revises: 195846028005
Create Date: 2026-01-15 08:01:57.457105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "897baf33d221"
down_revision: Union[str, Sequence[str], None] = "195846028005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column(
        "blowers", sa.Column("current_power_percentage", sa.Float(), nullable=True)
    )

    # Step 2: Set default value for existing rows (copy from power_percentage)
    op.execute(
        "UPDATE blowers SET current_power_percentage = power_percentage WHERE current_power_percentage IS NULL"
    )

    # Step 3: Make it NOT NULL
    op.alter_column("blowers", "current_power_percentage", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blowers", "current_power_percentage")
    # ### end Alembic commands ###
