"""create cage_groups table

Revision ID: 757cae81d594
Revises: 63b3eb34cf92
Create Date: 2026-01-19 14:29:24.766482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '757cae81d594'
down_revision: Union[str, Sequence[str], None] = '63b3eb34cf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create cage_groups table
    op.create_table('cage_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cage_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.CheckConstraint('length(cage_ids) > 2', name='cage_ids_not_empty')
    )
    # Create indexes for cage_groups
    op.create_index('idx_cage_groups_name', 'cage_groups', ['name'], unique=False)
    op.create_table('cage_biometry_log',
    sa.Column('biometry_id', sa.Uuid(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.Column('old_fish_count', sa.Integer(), nullable=True),
    sa.Column('old_average_weight_g', sa.Float(), nullable=True),
    sa.Column('new_fish_count', sa.Integer(), nullable=True),
    sa.Column('new_average_weight_g', sa.Float(), nullable=True),
    sa.Column('sampling_date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('biometry_id')
    )
    op.create_index(op.f('ix_cage_biometry_log_cage_id'), 'cage_biometry_log', ['cage_id'], unique=False)
    op.create_table('cage_config_changes_log',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index(op.f('ix_cage_config_changes_log_cage_id'), 'cage_config_changes_log', ['cage_id'], unique=False)
    op.create_index(op.f('ix_cage_config_changes_log_created_at'), 'cage_config_changes_log', ['created_at'], unique=False)
    op.create_table('cage_mortality_log',
    sa.Column('mortality_id', sa.Uuid(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.Column('dead_fish_count', sa.Integer(), nullable=False),
    sa.Column('mortality_date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mortality_id')
    )
    op.create_index(op.f('ix_cage_mortality_log_cage_id'), 'cage_mortality_log', ['cage_id'], unique=False)
    op.create_index(op.f('ix_cage_mortality_log_mortality_date'), 'cage_mortality_log', ['mortality_date'], unique=False)
    op.drop_constraint(op.f('uq_slot_assignments_cage_id'), 'slot_assignments', type_='unique')
    op.drop_constraint(op.f('uq_slot_assignments_line_slot'), 'slot_assignments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_slot_assignments_line_slot'), 'slot_assignments', ['line_id', 'slot_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_slot_assignments_cage_id'), 'slot_assignments', ['cage_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cage_mortality_log_mortality_date'), table_name='cage_mortality_log')
    op.drop_index(op.f('ix_cage_mortality_log_cage_id'), table_name='cage_mortality_log')
    op.drop_table('cage_mortality_log')
    op.drop_index(op.f('ix_cage_config_changes_log_created_at'), table_name='cage_config_changes_log')
    op.drop_index(op.f('ix_cage_config_changes_log_cage_id'), table_name='cage_config_changes_log')
    op.drop_table('cage_config_changes_log')
    op.drop_index(op.f('ix_cage_biometry_log_cage_id'), table_name='cage_biometry_log')
    op.drop_table('cage_biometry_log')
    # Drop cage_groups indexes and table
    op.drop_index('idx_cage_groups_name', table_name='cage_groups')
    op.drop_table('cage_groups')
    # ### end Alembic commands ###
