"""Add feeding session, cage feeding and events tables

Revision ID: e7a46278866f
Revises: 8df8112aa13a
Create Date: 2026-02-16 14:47:44.809499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7a46278866f'
down_revision: Union[str, Sequence[str], None] = '8df8112aa13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop index on cage_groups
    op.drop_index(op.f('idx_cage_groups_name'), table_name='cage_groups')

    # Step 2: Drop ALL foreign key constraints that reference feeding_sessions.id (BEFORE changing its type)
    op.drop_constraint(op.f('feeding_events_session_id_fkey'), 'feeding_events', type_='foreignkey')
    op.drop_constraint(op.f('feeding_operations_session_id_fkey'), 'feeding_operations', type_='foreignkey')

    # Step 3: Modify feeding_sessions table (must happen BEFORE creating cage_feedings)
    op.alter_column('feeding_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('feeding_sessions', sa.Column('operator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('feeding_sessions', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('feeding_sessions', sa.Column('allow_overtime', sa.Boolean(), nullable=False))
    op.add_column('feeding_sessions', sa.Column('total_programmed_kg', sa.Float(), nullable=False))
    op.add_column('feeding_sessions', sa.Column('scheduled_start', sa.DateTime(), nullable=True))
    op.add_column('feeding_sessions', sa.Column('actual_start', sa.DateTime(), nullable=True))
    op.add_column('feeding_sessions', sa.Column('actual_end', sa.DateTime(), nullable=True))
    op.add_column('feeding_sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_feeding_sessions_date'), table_name='feeding_sessions')
    op.create_index(op.f('ix_feeding_sessions_actual_start'), 'feeding_sessions', ['actual_start'], unique=False)
    op.create_index(op.f('ix_feeding_sessions_created_at'), 'feeding_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_feeding_sessions_operator_id'), 'feeding_sessions', ['operator_id'], unique=False)
    op.create_index(op.f('ix_feeding_sessions_type'), 'feeding_sessions', ['type'], unique=False)
    op.drop_column('feeding_sessions', 'dispensed_by_slot')
    op.drop_column('feeding_sessions', 'total_dispensed_kg')
    op.drop_column('feeding_sessions', 'date')

    # Step 4: Modify feeding_events table
    op.alter_column('feeding_events', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('feeding_events', sa.Column('feeding_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('feeding_events', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_feeding_events_session_id'), table_name='feeding_events')
    op.create_index(op.f('ix_feeding_events_event_type'), 'feeding_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_feeding_events_feeding_session_id'), 'feeding_events', ['feeding_session_id'], unique=False)
    op.create_foreign_key(None, 'feeding_events', 'feeding_sessions', ['feeding_session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('feeding_events', 'session_id')
    op.drop_column('feeding_events', 'details')
    op.drop_column('feeding_events', 'description')

    # Step 5: Convert feeding_operations.session_id from UUID to VARCHAR to match feeding_sessions.id
    op.alter_column('feeding_operations', 'session_id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)

    # Step 5.1: Recreate foreign key constraint for feeding_operations (now that both columns are VARCHAR)
    op.create_foreign_key(op.f('feeding_operations_session_id_fkey'), 'feeding_operations', 'feeding_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # Step 6: Create cage_feedings table (now that feeding_sessions.id is VARCHAR)
    op.create_table('cage_feedings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feeding_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cage_id', sa.Uuid(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('programmed_kg', sa.Float(), nullable=False),
    sa.Column('programmed_visits', sa.Integer(), nullable=False),
    sa.Column('rate_kg_per_min', sa.Float(), nullable=False),
    sa.Column('dispensed_kg', sa.Float(), nullable=False),
    sa.Column('completed_visits', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feeding_session_id'], ['feeding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cage_feedings_cage_id'), 'cage_feedings', ['cage_id'], unique=False)
    op.create_index(op.f('ix_cage_feedings_created_at'), 'cage_feedings', ['created_at'], unique=False)
    op.create_index(op.f('ix_cage_feedings_feeding_session_id'), 'cage_feedings', ['feeding_session_id'], unique=False)
    op.create_index(op.f('ix_cage_feedings_status'), 'cage_feedings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop cage_feedings table (reverse of last step in upgrade)
    op.drop_index(op.f('ix_cage_feedings_status'), table_name='cage_feedings')
    op.drop_index(op.f('ix_cage_feedings_feeding_session_id'), table_name='cage_feedings')
    op.drop_index(op.f('ix_cage_feedings_created_at'), table_name='cage_feedings')
    op.drop_index(op.f('ix_cage_feedings_cage_id'), table_name='cage_feedings')
    op.drop_table('cage_feedings')

    # Step 2: Drop foreign key from feeding_operations (BEFORE changing feeding_sessions.id type back)
    op.drop_constraint(op.f('feeding_operations_session_id_fkey'), 'feeding_operations', type_='foreignkey')

    # Step 3: Restore feeding_events table to old structure
    op.add_column('feeding_events', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('feeding_events', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('feeding_events', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feeding_events', type_='foreignkey')
    op.create_foreign_key(op.f('feeding_events_session_id_fkey'), 'feeding_events', 'feeding_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_feeding_events_feeding_session_id'), table_name='feeding_events')
    op.drop_index(op.f('ix_feeding_events_event_type'), table_name='feeding_events')
    op.create_index(op.f('ix_feeding_events_session_id'), 'feeding_events', ['session_id'], unique=False)
    op.alter_column('feeding_events', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('feeding_events', 'data')
    op.drop_column('feeding_events', 'feeding_session_id')

    # Step 4: Restore feeding_sessions table to old structure
    op.add_column('feeding_sessions', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('feeding_sessions', sa.Column('total_dispensed_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('feeding_sessions', sa.Column('dispensed_by_slot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_feeding_sessions_type'), table_name='feeding_sessions')
    op.drop_index(op.f('ix_feeding_sessions_operator_id'), table_name='feeding_sessions')
    op.drop_index(op.f('ix_feeding_sessions_created_at'), table_name='feeding_sessions')
    op.drop_index(op.f('ix_feeding_sessions_actual_start'), table_name='feeding_sessions')
    op.create_index(op.f('ix_feeding_sessions_date'), 'feeding_sessions', ['date'], unique=False)
    op.alter_column('feeding_sessions', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('feeding_sessions', 'created_at')
    op.drop_column('feeding_sessions', 'actual_end')
    op.drop_column('feeding_sessions', 'actual_start')
    op.drop_column('feeding_sessions', 'scheduled_start')
    op.drop_column('feeding_sessions', 'total_programmed_kg')
    op.drop_column('feeding_sessions', 'allow_overtime')
    op.drop_column('feeding_sessions', 'type')
    op.drop_column('feeding_sessions', 'operator_id')

    # Step 5: Convert feeding_operations.session_id back to UUID to match feeding_sessions.id
    op.alter_column('feeding_operations', 'session_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)

    # Step 5.1: Recreate foreign key for feeding_operations (now that both columns are UUID again)
    op.create_foreign_key(op.f('feeding_operations_session_id_fkey'), 'feeding_operations', 'feeding_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # Step 6: Restore cage_groups index
    op.create_index(op.f('idx_cage_groups_name'), 'cage_groups', ['name'], unique=False)
    # ### end Alembic commands ###
