"""add_current_slot_to_selector

Revision ID: 195846028005
Revises: 72b8645b702a
Create Date: 2026-01-15 07:35:47.410648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195846028005'
down_revision: Union[str, Sequence[str], None] = '72b8645b702a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selectors', sa.Column('current_slot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selectors', 'current_slot')
    # ### end Alembic commands ###
