"""add food entity and silo food_id relationship

Revision ID: 72b8645b702a
Revises: 69a72d3e5e93
Create Date: 2026-01-12 12:29:26.658678

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72b8645b702a"
down_revision: Union[str, Sequence[str], None] = "69a72d3e5e93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("ppk", sa.Float(), nullable=False),
        sa.Column("size_mm", sa.Float(), nullable=False),
        sa.Column("energy", sa.Float(), nullable=False),
        sa.Column("kg_per_liter", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("silos", sa.Column("food_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_silos_food_id", "silos", "foods", ["food_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_silos_food_id", "silos", type_="foreignkey")
    op.drop_column("silos", "food_id")
    op.drop_table("foods")
    # ### end Alembic commands ###
