"""add user_id to 11 root tables

Revision ID: 720a03b05d34
Revises: b0a9ccf76ebc
Create Date: 2026-03-02 14:27:45.624560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720a03b05d34'
down_revision: Union[str, Sequence[str], None] = 'b0a9ccf76ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'users', ['user_id'], ['id'])
    op.add_column('cage_groups', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('cage_groups_name_key'), 'cage_groups', type_='unique')
    op.create_index(op.f('ix_cage_groups_user_id'), 'cage_groups', ['user_id'], unique=False)
    op.create_unique_constraint('uq_cage_groups_name_user', 'cage_groups', ['name', 'user_id'])
    op.create_foreign_key(None, 'cage_groups', 'users', ['user_id'], ['id'])
    op.add_column('cages', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('cages_name_key'), 'cages', type_='unique')
    op.create_index(op.f('ix_cages_user_id'), 'cages', ['user_id'], unique=False)
    op.create_unique_constraint('uq_cages_name_user', 'cages', ['name', 'user_id'])
    op.create_foreign_key(None, 'cages', 'users', ['user_id'], ['id'])
    op.add_column('feedback', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_foreign_key(None, 'feedback', 'users', ['user_id'], ['id'])
    op.add_column('feeding_lines', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('feeding_lines_name_key'), 'feeding_lines', type_='unique')
    op.create_index(op.f('ix_feeding_lines_user_id'), 'feeding_lines', ['user_id'], unique=False)
    op.create_unique_constraint('uq_feeding_lines_name_user', 'feeding_lines', ['name', 'user_id'])
    op.create_foreign_key(None, 'feeding_lines', 'users', ['user_id'], ['id'])
    op.add_column('feeding_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_feeding_sessions_user_id'), 'feeding_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'feeding_sessions', 'users', ['user_id'], ['id'])
    op.add_column('foods', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('foods_code_key'), 'foods', type_='unique')
    op.drop_constraint(op.f('foods_name_key'), 'foods', type_='unique')
    op.create_index(op.f('ix_foods_user_id'), 'foods', ['user_id'], unique=False)
    op.create_unique_constraint('uq_foods_code_user', 'foods', ['code', 'user_id'])
    op.create_unique_constraint('uq_foods_name_user', 'foods', ['name', 'user_id'])
    op.create_foreign_key(None, 'foods', 'users', ['user_id'], ['id'])
    op.add_column('scheduled_alerts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_scheduled_alerts_user_id'), 'scheduled_alerts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'scheduled_alerts', 'users', ['user_id'], ['id'])
    op.add_column('silos', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('silos_name_key'), 'silos', type_='unique')
    op.create_index(op.f('ix_silos_user_id'), 'silos', ['user_id'], unique=False)
    op.create_unique_constraint('uq_silos_name_user', 'silos', ['name', 'user_id'])
    op.create_foreign_key(None, 'silos', 'users', ['user_id'], ['id'])
    op.add_column('slot_assignments', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_slot_assignments_user_id'), 'slot_assignments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'slot_assignments', 'users', ['user_id'], ['id'])
    op.add_column('system_config', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_system_config_user_id'), 'system_config', ['user_id'], unique=False)
    op.create_unique_constraint('uq_system_config_user', 'system_config', ['user_id'])
    op.create_foreign_key(None, 'system_config', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_config', type_='foreignkey')
    op.drop_constraint('uq_system_config_user', 'system_config', type_='unique')
    op.drop_index(op.f('ix_system_config_user_id'), table_name='system_config')
    op.drop_column('system_config', 'user_id')
    op.drop_constraint(None, 'slot_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_slot_assignments_user_id'), table_name='slot_assignments')
    op.drop_column('slot_assignments', 'user_id')
    op.drop_constraint(None, 'silos', type_='foreignkey')
    op.drop_constraint('uq_silos_name_user', 'silos', type_='unique')
    op.drop_index(op.f('ix_silos_user_id'), table_name='silos')
    op.create_unique_constraint(op.f('silos_name_key'), 'silos', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('silos', 'user_id')
    op.drop_constraint(None, 'scheduled_alerts', type_='foreignkey')
    op.drop_index(op.f('ix_scheduled_alerts_user_id'), table_name='scheduled_alerts')
    op.drop_column('scheduled_alerts', 'user_id')
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.drop_constraint('uq_foods_name_user', 'foods', type_='unique')
    op.drop_constraint('uq_foods_code_user', 'foods', type_='unique')
    op.drop_index(op.f('ix_foods_user_id'), table_name='foods')
    op.create_unique_constraint(op.f('foods_name_key'), 'foods', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('foods_code_key'), 'foods', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('foods', 'user_id')
    op.drop_constraint(None, 'feeding_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_feeding_sessions_user_id'), table_name='feeding_sessions')
    op.drop_column('feeding_sessions', 'user_id')
    op.drop_constraint(None, 'feeding_lines', type_='foreignkey')
    op.drop_constraint('uq_feeding_lines_name_user', 'feeding_lines', type_='unique')
    op.drop_index(op.f('ix_feeding_lines_user_id'), table_name='feeding_lines')
    op.create_unique_constraint(op.f('feeding_lines_name_key'), 'feeding_lines', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('feeding_lines', 'user_id')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_column('feedback', 'user_id')
    op.drop_constraint(None, 'cages', type_='foreignkey')
    op.drop_constraint('uq_cages_name_user', 'cages', type_='unique')
    op.drop_index(op.f('ix_cages_user_id'), table_name='cages')
    op.create_unique_constraint(op.f('cages_name_key'), 'cages', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('cages', 'user_id')
    op.drop_constraint(None, 'cage_groups', type_='foreignkey')
    op.drop_constraint('uq_cage_groups_name_user', 'cage_groups', type_='unique')
    op.drop_index(op.f('ix_cage_groups_user_id'), table_name='cage_groups')
    op.create_unique_constraint(op.f('cage_groups_name_key'), 'cage_groups', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('cage_groups', 'user_id')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_column('alerts', 'user_id')
    # ### end Alembic commands ###
