"""add system_config table

Revision ID: a1c83d7f0c16
Revises: f3a4b5c6d7e8
Create Date: 2026-02-17 21:21:44.055280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1c83d7f0c16'
down_revision: Union[str, Sequence[str], None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feeding_start_time', sa.Time(), nullable=False),
    sa.Column('feeding_end_time', sa.Time(), nullable=False),
    sa.Column('timezone_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Tablas del sistema antiguo — ya no se usan
    op.drop_table('operation_events')
    op.drop_table('feeding_operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding_operations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cage_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('target_slot', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_amount_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dispensed_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('applied_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.id'], name='feeding_operations_cage_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['feeding_sessions.id'], name='feeding_operations_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feeding_operations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_feeding_operations_status'), 'feeding_operations', ['status'], unique=False)
    op.create_index(op.f('ix_feeding_operations_started_at'), 'feeding_operations', ['started_at'], unique=False)
    op.create_index(op.f('ix_feeding_operations_session_id'), 'feeding_operations', ['session_id'], unique=False)
    op.create_index(op.f('ix_feeding_operations_cage_id'), 'feeding_operations', ['cage_id'], unique=False)
    op.create_table('operation_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['feeding_operations.id'], name=op.f('operation_events_operation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('operation_events_pkey'))
    )
    op.create_index(op.f('ix_operation_events_timestamp'), 'operation_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_operation_events_operation_id'), 'operation_events', ['operation_id'], unique=False)
    op.drop_table('system_config')
    # ### end Alembic commands ###
